# Generated by Django 4.2.5 on 2023-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('status', models.CharField(choices=[('Aguardando início', 'Aguardando início'), ('Arquivado', 'Arquivado')], default='Aguardando início', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
